METHOD_NAME: 'Res50+CLIP+NLP_AUG+COLOR+ID_CLS'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 20
  BASE_LR: 2e-5
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-5
  COLOR: True
  TYPE: False
  ID: True

MODEL:
  SPLIT_TEXT: False

DATA:
  SIZE: 384