METHOD_NAME: 'Res50+GRU+CLIP+NLP_AUG+COLOR+SPLIT'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 20
  BASE_LR: 2e-5
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-5
  COLOR: True
  TYPE: False

MODEL:
  SPLIT_TEXT: True

DATA:
  SIZE: 384